"""
根据 `justpy.htmlcomponents.py:component_by_tag` 可知, justpy 支持的 tag 相当于
把 `justpy.htmlcomponents.py` 顶层的所有以大写字母开头的对象名 (包括变量名, 函数
名, 类名) 作为了 Component.
因此我们也可以利用此规则, 创建出 "内置" 的 HTML Components.
生成结果见: `justpy_declarative/components/html_components.py`
"""
from textwrap import dedent
from lk_utils.read_and_write import dumps, load_list


def _fmt_string(s: str):
    return dedent(s)[1:]


# the `file_template` relates to `justpy_declarative/components/html_components
# .py`, you can consider it as so.
file_template = _fmt_string('''
    """
    Notes:
        This file is auto generated by `blueprint/generate_components_by_tag.py`.
    
    Usages:
        from justpy_declarative import app, WebPage, Div
        
        with Application() as app:
            with WebPage() as page:
                with Div() as div:
                    div.text = 'Hello World'
            app.start(page)
    """
    import justpy
    
    from .base_component import BaseComponent
    
    
    {HTML_COMPONENTS}
''')

template = _fmt_string('''
    class {TAG_NAME}(justpy.{TAG_NAME}, BaseComponent):
        pass
''')

html_components = []

for tag in load_list('html_tags.txt'):
    #   该文件中的 tags 是从 `justpy.htmlcomponents.py` 中手动找出来的.
    if tag == '': continue
    html_components.append(
        template.format(TAG_NAME=tag)
    )
    

dumps(
    file_template.format(HTML_COMPONENTS='\n\n'.join(html_components)).rstrip(),
    '../justpy_declarative/components/html_components.py'
)
