"""
Notes:
    This file is auto generated by `blueprint/generate_components_by_tag.py`.

Usages:
    from justpy_declarative import app, WebPage, Div

    with Application() as app:
        with WebPage() as page:
            with Div() as div:
                div.text = 'Hello World'
        app.start(page)
"""
import justpy

from .base_component import BaseComponent


class WebPage(justpy.WebPage, BaseComponent):
    pass


class TailwindUIPage(justpy.TailwindUIPage, BaseComponent):
    pass


class AutoTable(justpy.AutoTable, BaseComponent):
    pass


class Hello(justpy.Hello, BaseComponent):
    pass


class HTMLBaseComponent(justpy.HTMLBaseComponent, BaseComponent):
    pass


class HTMLEntity(justpy.HTMLEntity, BaseComponent):
    pass


class JustpyBaseComponent(justpy.JustpyBaseComponent, BaseComponent):
    pass


class QHello(justpy.QHello, BaseComponent):
    pass


class Div(justpy.Div, BaseComponent):
    pass


class Input(justpy.Input, BaseComponent):
    pass


class Form(justpy.Form, BaseComponent):
    pass


class Label(justpy.Label, BaseComponent):
    pass


class Textarea(justpy.Textarea, BaseComponent):
    pass


class Select(justpy.Select, BaseComponent):
    pass


class A(justpy.A, BaseComponent):
    pass


class Link(justpy.Link, BaseComponent):
    pass


class Icon(justpy.Icon, BaseComponent):
    pass


class EditorMD(justpy.EditorMD, BaseComponent):
    pass


class Space(justpy.Space, BaseComponent):
    pass


class TabGroup(justpy.TabGroup, BaseComponent):
    pass


class Address(justpy.Address, BaseComponent):
    pass


class Article(justpy.Article, BaseComponent):
    pass


class Aside(justpy.Aside, BaseComponent):
    pass


class Footer(justpy.Footer, BaseComponent):
    pass


class Header(justpy.Header, BaseComponent):
    pass


class H1(justpy.H1, BaseComponent):
    pass


class H2(justpy.H2, BaseComponent):
    pass


class H3(justpy.H3, BaseComponent):
    pass


class H4(justpy.H4, BaseComponent):
    pass


class H5(justpy.H5, BaseComponent):
    pass


class H6(justpy.H6, BaseComponent):
    pass


class Main(justpy.Main, BaseComponent):
    pass


class Nav(justpy.Nav, BaseComponent):
    pass


class Section(justpy.Section, BaseComponent):
    pass


class Blockquote(justpy.Blockquote, BaseComponent):
    pass


class Dd(justpy.Dd, BaseComponent):
    pass


class Dl(justpy.Dl, BaseComponent):
    pass


class Dt(justpy.Dt, BaseComponent):
    pass


class Figcaption(justpy.Figcaption, BaseComponent):
    pass


class Figure(justpy.Figure, BaseComponent):
    pass


class Hr(justpy.Hr, BaseComponent):
    pass


class Li(justpy.Li, BaseComponent):
    pass


class Ol(justpy.Ol, BaseComponent):
    pass


class P(justpy.P, BaseComponent):
    pass


class Pre(justpy.Pre, BaseComponent):
    pass


class Ul(justpy.Ul, BaseComponent):
    pass


class Abbr(justpy.Abbr, BaseComponent):
    pass


class B(justpy.B, BaseComponent):
    pass


class Bdi(justpy.Bdi, BaseComponent):
    pass


class Bdo(justpy.Bdo, BaseComponent):
    pass


class Br(justpy.Br, BaseComponent):
    pass


class Cite(justpy.Cite, BaseComponent):
    pass


class Code(justpy.Code, BaseComponent):
    pass


class Data(justpy.Data, BaseComponent):
    pass


class Dfn(justpy.Dfn, BaseComponent):
    pass


class Em(justpy.Em, BaseComponent):
    pass


class I(justpy.I, BaseComponent):
    pass


class Kbd(justpy.Kbd, BaseComponent):
    pass


class Mark(justpy.Mark, BaseComponent):
    pass


class Q(justpy.Q, BaseComponent):
    pass


class Rb(justpy.Rb, BaseComponent):
    pass


class Rp(justpy.Rp, BaseComponent):
    pass


class Rt(justpy.Rt, BaseComponent):
    pass


class Rtc(justpy.Rtc, BaseComponent):
    pass


class Ruby(justpy.Ruby, BaseComponent):
    pass


class S(justpy.S, BaseComponent):
    pass


class Samp(justpy.Samp, BaseComponent):
    pass


class Small(justpy.Small, BaseComponent):
    pass


class Span(justpy.Span, BaseComponent):
    pass


class Strong(justpy.Strong, BaseComponent):
    pass


class Sub(justpy.Sub, BaseComponent):
    pass


class Sup(justpy.Sup, BaseComponent):
    pass


class Time(justpy.Time, BaseComponent):
    pass


class Tt(justpy.Tt, BaseComponent):
    pass


class U(justpy.U, BaseComponent):
    pass


class Var(justpy.Var, BaseComponent):
    pass


class Wbr(justpy.Wbr, BaseComponent):
    pass


class Area(justpy.Area, BaseComponent):
    pass


class Audio(justpy.Audio, BaseComponent):
    pass


class Img(justpy.Img, BaseComponent):
    pass


class Map(justpy.Map, BaseComponent):
    pass


class Track(justpy.Track, BaseComponent):
    pass


class Video(justpy.Video, BaseComponent):
    pass


class Embed(justpy.Embed, BaseComponent):
    pass


class Iframe(justpy.Iframe, BaseComponent):
    pass


class Object(justpy.Object, BaseComponent):
    pass


class Param(justpy.Param, BaseComponent):
    pass


class Picture(justpy.Picture, BaseComponent):
    pass


class Source(justpy.Source, BaseComponent):
    pass


class Del(justpy.Del, BaseComponent):
    pass


class Ins(justpy.Ins, BaseComponent):
    pass


class Caption(justpy.Caption, BaseComponent):
    pass


class Col(justpy.Col, BaseComponent):
    pass


class Colgroup(justpy.Colgroup, BaseComponent):
    pass


class Table(justpy.Table, BaseComponent):
    pass


class Tbody(justpy.Tbody, BaseComponent):
    pass


class Td(justpy.Td, BaseComponent):
    pass


class Tfoot(justpy.Tfoot, BaseComponent):
    pass


class Th(justpy.Th, BaseComponent):
    pass


class Thead(justpy.Thead, BaseComponent):
    pass


class Tr(justpy.Tr, BaseComponent):
    pass


class Button(justpy.Button, BaseComponent):
    pass


class Fieldset(justpy.Fieldset, BaseComponent):
    pass


class Legend(justpy.Legend, BaseComponent):
    pass


class Meter(justpy.Meter, BaseComponent):
    pass


class Optgroup(justpy.Optgroup, BaseComponent):
    pass


class Option(justpy.Option, BaseComponent):
    pass


class Progress(justpy.Progress, BaseComponent):
    pass


class Details(justpy.Details, BaseComponent):
    pass


class Summary(justpy.Summary, BaseComponent):
    pass


class Animate(justpy.Animate, BaseComponent):
    pass


class AnimateMotion(justpy.AnimateMotion, BaseComponent):
    pass


class AnimateTransform(justpy.AnimateTransform, BaseComponent):
    pass


class Circle(justpy.Circle, BaseComponent):
    pass


class ClipPath(justpy.ClipPath, BaseComponent):
    pass


class Defs(justpy.Defs, BaseComponent):
    pass


class Desc(justpy.Desc, BaseComponent):
    pass


class Discard(justpy.Discard, BaseComponent):
    pass


class Ellipse(justpy.Ellipse, BaseComponent):
    pass


class FeBlend(justpy.FeBlend, BaseComponent):
    pass


class FeColorMatrix(justpy.FeColorMatrix, BaseComponent):
    pass


class FeComponentTransfer(justpy.FeComponentTransfer, BaseComponent):
    pass


class FeComposite(justpy.FeComposite, BaseComponent):
    pass


class FeConvolveMatrix(justpy.FeConvolveMatrix, BaseComponent):
    pass


class FeDiffuseLighting(justpy.FeDiffuseLighting, BaseComponent):
    pass


class FeDisplacementMap(justpy.FeDisplacementMap, BaseComponent):
    pass


class FeDistantLight(justpy.FeDistantLight, BaseComponent):
    pass


class FeDropShadow(justpy.FeDropShadow, BaseComponent):
    pass


class FeFlood(justpy.FeFlood, BaseComponent):
    pass


class FeFuncA(justpy.FeFuncA, BaseComponent):
    pass


class FeFuncB(justpy.FeFuncB, BaseComponent):
    pass


class FeFuncG(justpy.FeFuncG, BaseComponent):
    pass


class FeFuncR(justpy.FeFuncR, BaseComponent):
    pass


class FeGaussianBlur(justpy.FeGaussianBlur, BaseComponent):
    pass


class FeImage(justpy.FeImage, BaseComponent):
    pass


class FeMerge(justpy.FeMerge, BaseComponent):
    pass


class FeMergeNode(justpy.FeMergeNode, BaseComponent):
    pass


class FeMorphology(justpy.FeMorphology, BaseComponent):
    pass


class FeOffset(justpy.FeOffset, BaseComponent):
    pass


class FePointLight(justpy.FePointLight, BaseComponent):
    pass


class FeSpecularLighting(justpy.FeSpecularLighting, BaseComponent):
    pass


class FeSpotLight(justpy.FeSpotLight, BaseComponent):
    pass


class FeTile(justpy.FeTile, BaseComponent):
    pass


class FeTurbulence(justpy.FeTurbulence, BaseComponent):
    pass


class Filter(justpy.Filter, BaseComponent):
    pass


class ForeignObject(justpy.ForeignObject, BaseComponent):
    pass


class G(justpy.G, BaseComponent):
    pass


class Image(justpy.Image, BaseComponent):
    pass


class Line(justpy.Line, BaseComponent):
    pass


class LinearGradient(justpy.LinearGradient, BaseComponent):
    pass


class Marker(justpy.Marker, BaseComponent):
    pass


class Mask(justpy.Mask, BaseComponent):
    pass


class Metadata(justpy.Metadata, BaseComponent):
    pass


class Mpath(justpy.Mpath, BaseComponent):
    pass


class Path(justpy.Path, BaseComponent):
    pass


class Pattern(justpy.Pattern, BaseComponent):
    pass


class Polygon(justpy.Polygon, BaseComponent):
    pass


class Polyline(justpy.Polyline, BaseComponent):
    pass


class RadialGradient(justpy.RadialGradient, BaseComponent):
    pass


class Rect(justpy.Rect, BaseComponent):
    pass


class Set(justpy.Set, BaseComponent):
    pass


class Stop(justpy.Stop, BaseComponent):
    pass


class Svg(justpy.Svg, BaseComponent):
    pass


class Switch(justpy.Switch, BaseComponent):
    pass


class Symbol(justpy.Symbol, BaseComponent):
    pass


class Text(justpy.Text, BaseComponent):
    pass


class TextPath(justpy.TextPath, BaseComponent):
    pass


class Tspan(justpy.Tspan, BaseComponent):
    pass


class Use(justpy.Use, BaseComponent):
    pass


class View(justpy.View, BaseComponent):
    pass
